# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Inventory' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Inventory
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'Gallery'
    pod 'SDWebImage', '~> 4.0'
    pod 'SVProgressHUD'
end
